[package]
name = "homework"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Tobias Follett"]
license = "MIT"
description = "Homework template"
categories = ["homework"]
disciplines = ["mathematics", "physics"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
